/**
 * Custom LMS content-api routes.
 * Policies enforce role gates; student identity always comes from JWT.
 */
export default {
  type: 'content-api' as const,
  routes: [
    {
      method: 'GET',
      path: '/lms/me',
      handler: 'lms.me',
      // JWT verified in service — bypasses users-permissions action matrix
      config: { auth: false },
    },
    {
      method: 'PUT',
      path: '/lms/me',
      handler: 'lms.updateMe',
      config: { policies: ['global::is-authenticated'] },
    },
    {
      method: 'POST',
      path: '/lms/me/password',
      handler: 'lms.changeMyPassword',
      config: { policies: ['global::is-authenticated'] },
    },
    {
      method: 'POST',
      path: '/lms/enroll/:courseId',
      handler: 'lms.enroll',
      config: { policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/my-courses',
      handler: 'lms.myCourses',
      config: { policies: ['global::is-authenticated'] },
    },
    {
      method: 'POST',
      path: '/lms/lessons/:lessonId/complete',
      handler: 'lms.completeLesson',
      config: { policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/courses/:courseId/progress',
      handler: 'lms.courseProgress',
      config: { policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/quizzes/:quizId/take',
      handler: 'lms.takeQuiz',
      config: { policies: ['global::is-authenticated'] },
    },
    {
      method: 'POST',
      path: '/lms/quizzes/:quizId/submit',
      handler: 'lms.submitQuiz',
      config: { policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/quizzes/:quizId/attempts',
      handler: 'lms.quizAttempts',
      config: { policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/dashboard/student',
      handler: 'lms.studentDashboard',
      config: { policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/dashboard/instructor',
      handler: 'lms.instructorDashboard',
      config: { policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'GET',
      path: '/lms/dashboard/content-manager',
      handler: 'lms.contentManagerDashboard',
      config: { policies: ['global::is-content-manager-or-admin'] },
    },
    {
      method: 'GET',
      path: '/lms/staff/courses',
      handler: 'lms.staffListCourses',
      config: { policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/dashboard/admin',
      handler: 'lms.adminDashboard',
      config: { policies: ['global::is-admin'] },
    },
    {
      method: 'GET',
      path: '/lms/admin/users',
      handler: 'lms.adminListUsers',
      config: { policies: ['global::is-admin'] },
    },
    {
      method: 'PATCH',
      path: '/lms/admin/users/:userId/role',
      handler: 'lms.adminUpdateUserRole',
      config: { policies: ['global::is-admin'] },
    },
    {
      method: 'PATCH',
      path: '/lms/admin/users/:userId/status',
      handler: 'lms.adminUpdateUserStatus',
      config: { policies: ['global::is-admin'] },
    },
    {
      method: 'POST',
      path: '/lms/admin/users',
      handler: 'lms.adminCreateUser',
      config: { policies: ['global::is-admin'] },
    },
    {
      method: 'DELETE',
      path: '/lms/admin/users/:userId',
      handler: 'lms.adminDeleteUser',
      config: { policies: ['global::is-admin'] },
    },
    {
      method: 'GET',
      path: '/lms/certificates/me',
      handler: 'lms.myCertificates',
      config: { policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/certificates/:id',
      handler: 'lms.getCertificate',
      config: { policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/admin/certificates',
      handler: 'lms.adminListCertificates',
      config: { policies: ['global::is-admin'] },
    },
    {
      method: 'GET',
      path: '/lms/admin/enrollments',
      handler: 'lms.adminListEnrollments',
      config: { policies: ['global::is-admin'] },
    },
    {
      method: 'GET',
      path: '/lms/banners',
      handler: 'lms.listBanners',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/lms/admin/banners',
      handler: 'lms.adminListBanners',
      config: { policies: ['global::is-content-manager-or-admin'] },
    },
    {
      method: 'POST',
      path: '/lms/admin/banners',
      handler: 'lms.adminCreateBanner',
      config: { policies: ['global::is-content-manager-or-admin'] },
    },
    {
      method: 'PUT',
      path: '/lms/admin/banners/:id',
      handler: 'lms.adminUpdateBanner',
      config: { policies: ['global::is-content-manager-or-admin'] },
    },
    {
      method: 'DELETE',
      path: '/lms/admin/banners/:id',
      handler: 'lms.adminDeleteBanner',
      config: { policies: ['global::is-content-manager-or-admin'] },
    },
    {
      method: 'GET',
      path: '/lms/admin/coupons',
      handler: 'lms.adminListCoupons',
      config: { policies: ['global::is-admin'] },
    },
    {
      method: 'POST',
      path: '/lms/admin/coupons',
      handler: 'lms.adminCreateCoupon',
      config: { policies: ['global::is-admin'] },
    },
    {
      method: 'PUT',
      path: '/lms/admin/coupons/:id',
      handler: 'lms.adminUpdateCoupon',
      config: { policies: ['global::is-admin'] },
    },
    {
      method: 'DELETE',
      path: '/lms/admin/coupons/:id',
      handler: 'lms.adminDeleteCoupon',
      config: { policies: ['global::is-admin'] },
    },
    {
      method: 'POST',
      path: '/lms/coupons/validate',
      handler: 'lms.validateCoupon',
      config: { policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/courses/:courseId/player',
      handler: 'lms.getCoursePlayer',
      config: { policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/catalog',
      handler: 'lms.listCatalog',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/lms/catalog/:slug',
      handler: 'lms.getCatalogCourse',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/lms/categories',
      handler: 'lms.listCategories',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/lms/admin/categories',
      handler: 'lms.adminListCategories',
      config: { policies: ['global::is-content-manager-or-admin'] },
    },
    {
      method: 'POST',
      path: '/lms/admin/categories',
      handler: 'lms.adminCreateCategory',
      config: { policies: ['global::is-content-manager-or-admin'] },
    },
    {
      method: 'PUT',
      path: '/lms/admin/categories/:id',
      handler: 'lms.adminUpdateCategory',
      config: { policies: ['global::is-content-manager-or-admin'] },
    },
    {
      method: 'DELETE',
      path: '/lms/admin/categories/:id',
      handler: 'lms.adminDeleteCategory',
      config: { policies: ['global::is-content-manager-or-admin'] },
    },
    {
      method: 'GET',
      path: '/lms/courses/:courseId/modules',
      handler: 'lms.listCourseModules',
      config: { policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'POST',
      path: '/lms/courses/:courseId/modules',
      handler: 'lms.createCourseModule',
      config: { policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'PUT',
      path: '/lms/modules/:id',
      handler: 'lms.updateCourseModule',
      config: { policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'DELETE',
      path: '/lms/modules/:id',
      handler: 'lms.deleteCourseModule',
      config: { policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'POST',
      path: '/lms/courses',
      handler: 'lms.createCourse',
      config: { policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'PUT',
      path: '/lms/courses/:id',
      handler: 'lms.updateCourse',
      config: { policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'DELETE',
      path: '/lms/courses/:id',
      handler: 'lms.deleteCourse',
      config: { policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'POST',
      path: '/lms/courses/:courseId/lessons',
      handler: 'lms.createLesson',
      config: { policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'PUT',
      path: '/lms/lessons/:id',
      handler: 'lms.updateLesson',
      config: { policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'DELETE',
      path: '/lms/lessons/:id',
      handler: 'lms.deleteLesson',
      config: { policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'POST',
      path: '/lms/courses/:courseId/quizzes',
      handler: 'lms.createQuiz',
      config: { policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'PUT',
      path: '/lms/quizzes/:id',
      handler: 'lms.updateQuiz',
      config: { policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'DELETE',
      path: '/lms/quizzes/:id',
      handler: 'lms.deleteQuiz',
      config: { policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'GET',
      path: '/lms/blog',
      handler: 'lms.listBlog',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/lms/blog/manage',
      handler: 'lms.manageBlog',
      config: { policies: ['global::is-content-manager-or-admin'] },
    },
    {
      method: 'GET',
      path: '/lms/blog/:slug',
      handler: 'lms.getBlogBySlug',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/lms/blog',
      handler: 'lms.createBlog',
      config: { policies: ['global::is-content-manager-or-admin'] },
    },
    {
      method: 'PUT',
      path: '/lms/blog/:id',
      handler: 'lms.updateBlog',
      config: { policies: ['global::is-content-manager-or-admin'] },
    },
    {
      method: 'DELETE',
      path: '/lms/blog/:id',
      handler: 'lms.deleteBlog',
      config: { policies: ['global::is-content-manager-or-admin'] },
    },
    // Phase 3–8 ops
    {
      method: 'GET',
      path: '/lms/admin/people',
      handler: 'lms.adminListByRole',
      config: { policies: ['global::is-admin'] },
    },
    {
      method: 'POST',
      path: '/lms/admin/enrollments/force',
      handler: 'lms.adminForceEnroll',
      config: { policies: ['global::is-admin'] },
    },
    {
      method: 'DELETE',
      path: '/lms/admin/enrollments/:id',
      handler: 'lms.adminRemoveEnrollment',
      config: { policies: ['global::is-admin'] },
    },
    {
      method: 'GET',
      path: '/lms/admin/resources/:uid',
      handler: 'lms.adminCrudList',
      config: { policies: ['global::is-admin'] },
    },
    {
      method: 'POST',
      path: '/lms/admin/resources/:uid',
      handler: 'lms.adminCrudCreate',
      config: { policies: ['global::is-admin'] },
    },
    {
      method: 'PUT',
      path: '/lms/admin/resources/:uid/:id',
      handler: 'lms.adminCrudUpdate',
      config: { policies: ['global::is-admin'] },
    },
    {
      method: 'DELETE',
      path: '/lms/admin/resources/:uid/:id',
      handler: 'lms.adminCrudDelete',
      config: { policies: ['global::is-admin'] },
    },
    {
      method: 'POST',
      path: '/lms/admin/inventory/adjust',
      handler: 'lms.adminStockAdjust',
      config: { policies: ['global::is-admin'] },
    },
    {
      method: 'POST',
      path: '/lms/admin/certificates/:id/revoke',
      handler: 'lms.adminRevokeCertificate',
      config: { policies: ['global::is-admin'] },
    },
    {
      method: 'GET',
      path: '/lms/certificates/verify/:code',
      handler: 'lms.verifyCertificate',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/lms/orders',
      handler: 'lms.createOrderCheckout',
      config: { policies: ['global::is-authenticated'] },
    },
    {
      method: 'POST',
      path: '/lms/orders/:id/pay',
      handler: 'lms.payOrder',
      config: { policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/notifications/me',
      handler: 'lms.listMyNotifications',
      config: { policies: ['global::is-authenticated'] },
    },
    {
      method: 'POST',
      path: '/lms/notifications/:id/read',
      handler: 'lms.markNotificationRead',
      config: { policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/announcements',
      handler: 'lms.listAnnouncements',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/lms/admin/search',
      handler: 'lms.adminGlobalSearch',
      config: { policies: ['global::is-admin'] },
    },
    {
      method: 'GET',
      path: '/lms/admin/reports/summary',
      handler: 'lms.adminReportsSummary',
      config: { policies: ['global::is-admin'] },
    },
    {
      method: 'GET',
      path: '/lms/admin/settings',
      handler: 'lms.adminGetSettings',
      config: { policies: ['global::is-admin'] },
    },
    {
      method: 'PUT',
      path: '/lms/admin/settings',
      handler: 'lms.adminSaveSettings',
      config: { policies: ['global::is-admin'] },
    },
  ],
};
