/**
 * Custom LMS content-api routes.
 * Policies enforce role gates; student identity always comes from JWT.
 */
export default {
  type: 'content-api' as const,
  routes: [
    {
      method: 'GET',
      path: '/lms/me',
      handler: 'lms.me',
      // JWT verified in service — bypasses users-permissions action matrix
      config: { auth: false },
    },
    {
      method: 'PUT',
      path: '/lms/me',
      handler: 'lms.updateMe',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'POST',
      path: '/lms/me/password',
      handler: 'lms.changeMyPassword',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'POST',
      path: '/lms/enroll/:courseId',
      handler: 'lms.enroll',
      // auth:false skips users-permissions action matrix (generic Forbidden);
      // JWT + Student-only checks run in policy/service.
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/my-courses',
      handler: 'lms.myCourses',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'POST',
      path: '/lms/lessons/:lessonId/complete',
      handler: 'lms.completeLesson',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/courses/:courseId/progress',
      handler: 'lms.courseProgress',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/quizzes/:quizId/take',
      handler: 'lms.takeQuiz',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'POST',
      path: '/lms/quizzes/:quizId/submit',
      handler: 'lms.submitQuiz',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/quizzes/:quizId/attempts',
      handler: 'lms.quizAttempts',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/dashboard/student',
      handler: 'lms.studentDashboard',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/student/analytics',
      handler: 'lms.studentAnalytics',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/dashboard/instructor',
      handler: 'lms.instructorDashboard',
      config: { auth: false, policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'GET',
      path: '/lms/dashboard/content-manager',
      handler: 'lms.contentManagerDashboard',
      config: { auth: false, policies: ['global::is-content-manager-or-admin'] },
    },
    {
      method: 'GET',
      path: '/lms/staff/courses',
      handler: 'lms.staffListCourses',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/staff/progress',
      handler: 'lms.staffListProgress',
      config: { auth: false, policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'GET',
      path: '/lms/dashboard/admin',
      handler: 'lms.adminDashboard',
      config: { auth: false, policies: ['global::is-admin'] },
    },
    {
      method: 'GET',
      path: '/lms/admin/users',
      handler: 'lms.adminListUsers',
      config: { auth: false, policies: ['global::is-admin'] },
    },
    {
      method: 'PATCH',
      path: '/lms/admin/users/:userId/role',
      handler: 'lms.adminUpdateUserRole',
      config: { auth: false, policies: ['global::is-admin'] },
    },
    {
      method: 'PATCH',
      path: '/lms/admin/users/:userId/status',
      handler: 'lms.adminUpdateUserStatus',
      config: { auth: false, policies: ['global::is-admin'] },
    },
    {
      method: 'POST',
      path: '/lms/admin/users',
      handler: 'lms.adminCreateUser',
      config: { auth: false, policies: ['global::is-admin'] },
    },
    {
      method: 'DELETE',
      path: '/lms/admin/users/:userId',
      handler: 'lms.adminDeleteUser',
      config: { auth: false, policies: ['global::is-admin'] },
    },
    {
      method: 'GET',
      path: '/lms/certificates/me',
      handler: 'lms.myCertificates',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/certificates/:id',
      handler: 'lms.getCertificate',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/admin/certificates',
      handler: 'lms.adminListCertificates',
      config: { auth: false, policies: ['global::is-admin'] },
    },
    {
      method: 'GET',
      path: '/lms/admin/enrollments',
      handler: 'lms.adminListEnrollments',
      config: { auth: false, policies: ['global::is-admin'] },
    },
    {
      method: 'GET',
      path: '/lms/banners',
      handler: 'lms.listBanners',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/lms/admin/banners',
      handler: 'lms.adminListBanners',
      config: { auth: false, policies: ['global::is-content-manager-or-admin'] },
    },
    {
      method: 'POST',
      path: '/lms/admin/banners',
      handler: 'lms.adminCreateBanner',
      config: { auth: false, policies: ['global::is-content-manager-or-admin'] },
    },
    {
      method: 'PUT',
      path: '/lms/admin/banners/:id',
      handler: 'lms.adminUpdateBanner',
      config: { auth: false, policies: ['global::is-content-manager-or-admin'] },
    },
    {
      method: 'DELETE',
      path: '/lms/admin/banners/:id',
      handler: 'lms.adminDeleteBanner',
      config: { auth: false, policies: ['global::is-content-manager-or-admin'] },
    },
    {
      method: 'GET',
      path: '/lms/admin/coupons',
      handler: 'lms.adminListCoupons',
      config: { auth: false, policies: ['global::is-admin'] },
    },
    {
      method: 'POST',
      path: '/lms/admin/coupons',
      handler: 'lms.adminCreateCoupon',
      config: { auth: false, policies: ['global::is-admin'] },
    },
    {
      method: 'PUT',
      path: '/lms/admin/coupons/:id',
      handler: 'lms.adminUpdateCoupon',
      config: { auth: false, policies: ['global::is-admin'] },
    },
    {
      method: 'DELETE',
      path: '/lms/admin/coupons/:id',
      handler: 'lms.adminDeleteCoupon',
      config: { auth: false, policies: ['global::is-admin'] },
    },
    {
      method: 'POST',
      path: '/lms/coupons/validate',
      handler: 'lms.validateCoupon',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/courses/:courseId/player',
      handler: 'lms.getCoursePlayer',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/catalog',
      handler: 'lms.listCatalog',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/lms/catalog/:slug',
      handler: 'lms.getCatalogCourse',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/lms/categories',
      handler: 'lms.listCategories',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/lms/admin/categories',
      handler: 'lms.adminListCategories',
      config: { auth: false, policies: ['global::is-content-manager-or-admin'] },
    },
    {
      method: 'POST',
      path: '/lms/admin/categories',
      handler: 'lms.adminCreateCategory',
      config: { auth: false, policies: ['global::is-content-manager-or-admin'] },
    },
    {
      method: 'PUT',
      path: '/lms/admin/categories/:id',
      handler: 'lms.adminUpdateCategory',
      config: { auth: false, policies: ['global::is-content-manager-or-admin'] },
    },
    {
      method: 'DELETE',
      path: '/lms/admin/categories/:id',
      handler: 'lms.adminDeleteCategory',
      config: { auth: false, policies: ['global::is-content-manager-or-admin'] },
    },
    {
      method: 'GET',
      path: '/lms/courses/:courseId/modules',
      handler: 'lms.listCourseModules',
      config: { auth: false, policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'POST',
      path: '/lms/courses/:courseId/modules',
      handler: 'lms.createCourseModule',
      config: { auth: false, policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'PUT',
      path: '/lms/modules/:id',
      handler: 'lms.updateCourseModule',
      config: { auth: false, policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'DELETE',
      path: '/lms/modules/:id',
      handler: 'lms.deleteCourseModule',
      config: { auth: false, policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'POST',
      path: '/lms/courses',
      handler: 'lms.createCourse',
      config: { auth: false, policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'PUT',
      path: '/lms/courses/:id',
      handler: 'lms.updateCourse',
      config: { auth: false, policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'DELETE',
      path: '/lms/courses/:id',
      handler: 'lms.deleteCourse',
      config: { auth: false, policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'POST',
      path: '/lms/courses/:courseId/lessons',
      handler: 'lms.createLesson',
      config: { auth: false, policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'PUT',
      path: '/lms/lessons/:id',
      handler: 'lms.updateLesson',
      config: { auth: false, policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'DELETE',
      path: '/lms/lessons/:id',
      handler: 'lms.deleteLesson',
      config: { auth: false, policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'POST',
      path: '/lms/courses/:courseId/quizzes',
      handler: 'lms.createQuiz',
      config: { auth: false, policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'PUT',
      path: '/lms/quizzes/:id',
      handler: 'lms.updateQuiz',
      config: { auth: false, policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'DELETE',
      path: '/lms/quizzes/:id',
      handler: 'lms.deleteQuiz',
      config: { auth: false, policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'GET',
      path: '/lms/blog',
      handler: 'lms.listBlog',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/lms/blog/manage',
      handler: 'lms.manageBlog',
      config: { auth: false, policies: ['global::is-content-manager-or-admin'] },
    },
    {
      method: 'GET',
      path: '/lms/blog/:slug',
      handler: 'lms.getBlogBySlug',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/lms/blog',
      handler: 'lms.createBlog',
      config: { auth: false, policies: ['global::is-content-manager-or-admin'] },
    },
    {
      method: 'PUT',
      path: '/lms/blog/:id',
      handler: 'lms.updateBlog',
      config: { auth: false, policies: ['global::is-content-manager-or-admin'] },
    },
    {
      method: 'DELETE',
      path: '/lms/blog/:id',
      handler: 'lms.deleteBlog',
      config: { auth: false, policies: ['global::is-content-manager-or-admin'] },
    },
    // Phase 3–8 ops
    {
      method: 'GET',
      path: '/lms/admin/people',
      handler: 'lms.adminListByRole',
      config: { auth: false, policies: ['global::is-admin'] },
    },
    {
      method: 'POST',
      path: '/lms/admin/enrollments/force',
      handler: 'lms.adminForceEnroll',
      config: { auth: false, policies: ['global::is-admin'] },
    },
    {
      method: 'DELETE',
      path: '/lms/admin/enrollments/:id',
      handler: 'lms.adminRemoveEnrollment',
      config: { auth: false, policies: ['global::is-admin'] },
    },
    {
      method: 'GET',
      path: '/lms/admin/resources/:uid',
      handler: 'lms.adminCrudList',
      config: { auth: false, policies: ['global::is-admin'] },
    },
    {
      method: 'POST',
      path: '/lms/admin/resources/:uid',
      handler: 'lms.adminCrudCreate',
      config: { auth: false, policies: ['global::is-admin'] },
    },
    {
      method: 'PUT',
      path: '/lms/admin/resources/:uid/:id',
      handler: 'lms.adminCrudUpdate',
      config: { auth: false, policies: ['global::is-admin'] },
    },
    {
      method: 'DELETE',
      path: '/lms/admin/resources/:uid/:id',
      handler: 'lms.adminCrudDelete',
      config: { auth: false, policies: ['global::is-admin'] },
    },
    {
      method: 'POST',
      path: '/lms/admin/inventory/adjust',
      handler: 'lms.adminStockAdjust',
      config: { auth: false, policies: ['global::is-admin'] },
    },
    {
      method: 'POST',
      path: '/lms/admin/certificates/:id/revoke',
      handler: 'lms.adminRevokeCertificate',
      config: { auth: false, policies: ['global::is-admin'] },
    },
    {
      method: 'GET',
      path: '/lms/certificates/verify/:code',
      handler: 'lms.verifyCertificate',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/lms/orders',
      handler: 'lms.createOrderCheckout',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'POST',
      path: '/lms/orders/:id/pay',
      handler: 'lms.payOrder',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/notifications/me',
      handler: 'lms.listMyNotifications',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'POST',
      path: '/lms/notifications/read-all',
      handler: 'lms.markAllNotificationsRead',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'POST',
      path: '/lms/notifications/:id/read',
      handler: 'lms.markNotificationRead',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/announcements',
      handler: 'lms.listAnnouncements',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/lms/admin/search',
      handler: 'lms.adminGlobalSearch',
      config: { auth: false, policies: ['global::is-admin'] },
    },
    {
      method: 'GET',
      path: '/lms/admin/reports/summary',
      handler: 'lms.adminReportsSummary',
      config: { auth: false, policies: ['global::is-admin'] },
    },
    {
      method: 'GET',
      path: '/lms/admin/settings',
      handler: 'lms.adminGetSettings',
      config: { auth: false, policies: ['global::is-admin'] },
    },
    {
      method: 'PUT',
      path: '/lms/admin/settings',
      handler: 'lms.adminSaveSettings',
      config: { auth: false, policies: ['global::is-admin'] },
    },
    {
      method: 'GET',
      path: '/lms/assignments',
      handler: 'lms.listMyAssignments',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'POST',
      path: '/lms/assignments/:id/submit',
      handler: 'lms.submitAssignment',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/staff/assignments',
      handler: 'lms.staffListAssignments',
      config: { auth: false, policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'POST',
      path: '/lms/staff/assignments',
      handler: 'lms.staffCreateAssignment',
      config: { auth: false, policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'GET',
      path: '/lms/staff/assignments/:id/submissions',
      handler: 'lms.staffListSubmissions',
      config: { auth: false, policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'PATCH',
      path: '/lms/staff/submissions/:id/grade',
      handler: 'lms.staffGradeSubmission',
      config: { auth: false, policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'GET',
      path: '/lms/courses/:courseId/discussions',
      handler: 'lms.listCourseDiscussions',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'POST',
      path: '/lms/courses/:courseId/discussions',
      handler: 'lms.createCourseDiscussion',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'POST',
      path: '/lms/discussions/:id/replies',
      handler: 'lms.replyCourseDiscussion',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/courses/:courseId/reviews',
      handler: 'lms.listCourseReviews',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/lms/courses/:courseId/reviews',
      handler: 'lms.submitCourseReview',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/courses/:courseId/announcements',
      handler: 'lms.listCourseAnnouncements',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'POST',
      path: '/lms/courses/:courseId/announcements',
      handler: 'lms.createCourseAnnouncement',
      config: { auth: false, policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'GET',
      path: '/lms/courses/:courseId/question-bank',
      handler: 'lms.listCourseQuestionBank',
      config: { auth: false, policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'POST',
      path: '/lms/quizzes/:quizId/import-bank',
      handler: 'lms.importQuestionBankToQuiz',
      config: { auth: false, policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'GET',
      path: '/lms/courses/:courseId/live-sessions',
      handler: 'lms.listCourseLiveSessions',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'POST',
      path: '/lms/courses/:courseId/live-sessions',
      handler: 'lms.createCourseLiveSession',
      config: { auth: false, policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'GET',
      path: '/lms/tickets/me',
      handler: 'lms.listMyTickets',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'POST',
      path: '/lms/tickets/me',
      handler: 'lms.createMyTicket',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/wishlist',
      handler: 'lms.listMyWishlist',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'POST',
      path: '/lms/wishlist/:courseId',
      handler: 'lms.addWishlist',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'DELETE',
      path: '/lms/wishlist/:courseId',
      handler: 'lms.removeWishlist',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/courses/:courseId/analytics',
      handler: 'lms.instructorCourseAnalytics',
      config: { auth: false, policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'POST',
      path: '/lms/ai/assistant',
      handler: 'lms.aiAssistant',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/helpdesk/posts',
      handler: 'lms.listHelpDeskPosts',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'POST',
      path: '/lms/helpdesk/posts',
      handler: 'lms.createHelpDeskPost',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/messages',
      handler: 'lms.listMyMessages',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'POST',
      path: '/lms/messages',
      handler: 'lms.sendMessage',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'POST',
      path: '/lms/live-sessions/:id/attend',
      handler: 'lms.markLiveAttendance',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'POST',
      path: '/lms/wishlist/remind',
      handler: 'lms.runWishlistReminders',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/transcript',
      handler: 'lms.studentTranscript',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
    {
      method: 'GET',
      path: '/lms/courses/:courseId/grades.csv',
      handler: 'lms.exportCourseGradesCsv',
      config: { auth: false, policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'POST',
      path: '/lms/courses/:courseId/clone',
      handler: 'lms.cloneCourse',
      config: { auth: false, policies: ['global::is-instructor-or-above'] },
    },
    {
      method: 'GET',
      path: '/lms/live-calendar',
      handler: 'lms.listMyLiveCalendar',
      config: { auth: false, policies: ['global::is-authenticated'] },
    },
  ],
};
